const lang = {
  en: {
    appSubtitle: "Krishna Conscious Daily Tracker",
    greeting: "Hare Krishna",
    dailyProgress: "Daily Progress",
    score: "Score",
    streak: "Streak",
    done: "Done",
    pending: "Pending",
    todaySadhana: "Today's Sadhana",
    noTask: "No tasks. Add from 'Add' tab.",
    weeklyOverview: "Weekly Overview",
    addTitle: "Add / Edit Sadhana",
    timePlaceholder: "Time (e.g. 5:00 AM)",
    activityPlaceholder: "Activity (e.g. 16 rounds japa)",
    addBtn: "+ Add Activity",
    resetBtn: "🔄 Reset Today",
    currentTasks: "Current Tasks",
    timerTitle: "Sadhana Timer",
    timerRunning: "is running...",
    startBtn: "▶ Start",
    pauseBtn: "⏸ Pause",
    resetTimerBtn: "↺ Reset",
    timerDone: "complete!",
    ekTitle: "🌙 Upcoming Ekadashi",
    ekSubtitle: "2026 Ekadashi dates",
    today: "Today!",
    tomorrow: "Tomorrow",
    daysLeft: "days left",
    reportTitle: "📤 Sadhana Report",
    todayScore: "Today's Score",
    notesLabel: "Notes (will be sent on WhatsApp)",
    notesPlaceholder: "How was today's sadhna?",
    whatsappBtn: "📲 Send on WhatsApp",
    insightsTitle: "🤖 Sadhana Insights",
    analysisTitle: "📊 Today's Analysis",
    progress: "Progress",
    great: "Excellent! 🌟",
    ok: "Good, do more 💪",
    slow: "Slow today 🙏",
    streakMsg1: "Habit formed! 🎉",
    streakMsg2: "7 days done! 🔥",
    streakMsg3: "Build your streak!",
    suggTitle: "💡 Suggestions",
    suggPending: "tasks remaining — do now!",
    suggBrahma: "Brahma Muhurta (4-5 AM) sadhna is most powerful 🌅",
    shlokaTitle: "🕉️ Today's Shloka",
    logout: "🚪 Logout",
    loginTitle: "Sadhana OS",
    loginSub: "Krishna Conscious Daily Tracker",
    loginBtn: "Login with Google",
    loginFooter: "Track your sadhna, see your progress 🙏",
  },
  hi: {
    appSubtitle: "कृष्ण भावनामृत दैनिक ट्रैकर",
    greeting: "हरे कृष्ण",
    dailyProgress: "आज की प्रगति",
    score: "स्कोर",
    streak: "स्ट्रीक",
    done: "पूर्ण",
    pending: "बाकी",
    todaySadhana: "आज की साधना",
    noTask: "कोई कार्य नहीं। 'जोड़ें' से जोड़ें।",
    weeklyOverview: "साप्ताहिक अवलोकन",
    addTitle: "साधना जोड़ें / संपादित करें",
    timePlaceholder: "समय (जैसे सुबह 5:00)",
    activityPlaceholder: "गतिविधि (जैसे 16 माला जप)",
    addBtn: "+ गतिविधि जोड़ें",
    resetBtn: "🔄 आज रीसेट करें",
    currentTasks: "वर्तमान कार्य",
    timerTitle: "साधना टाइमर",
    timerRunning: "चल रहा है...",
    startBtn: "▶ शुरू",
    pauseBtn: "⏸ रोकें",
    resetTimerBtn: "↺ रीसेट",
    timerDone: "पूर्ण!",
    ekTitle: "🌙 आने वाली एकादशी",
    ekSubtitle: "2026 की एकादशी तिथियाँ",
    today: "आज!",
    tomorrow: "कल",
    daysLeft: "दिन में",
    reportTitle: "📤 साधना रिपोर्ट",
    todayScore: "आज का स्कोर",
    notesLabel: "नोट्स (WhatsApp पर जाएगा)",
    notesPlaceholder: "आज की साधना कैसी रही?",
    whatsappBtn: "📲 WhatsApp पर भेजें",
    insightsTitle: "🤖 साधना विश्लेषण",
    analysisTitle: "📊 आज का विश्लेषण",
    progress: "प्रगति",
    great: "बहुत अच्छा! 🌟",
    ok: "ठीक है, और करो 💪",
    slow: "आज थोड़ा कम 🙏",
    streakMsg1: "आदत बन गई! 🎉",
    streakMsg2: "7 दिन हो गए! 🔥",
    streakMsg3: "स्ट्रीक बढ़ाओ!",
    suggTitle: "💡 सुझाव",
    suggPending: "कार्य बाकी हैं — अभी करें!",
    suggBrahma: "ब्रह्म मुहूर्त (4-5 AM) में साधना सबसे शक्तिशाली होती है 🌅",
    shlokaTitle: "🕉️ आज का श्लोक",
    logout: "🚪 लॉगआउट",
    loginTitle: "साधना OS",
    loginSub: "कृष्ण भावनामृत दैनिक ट्रैकर",
    loginBtn: "Google से लॉगिन करें",
    loginFooter: "अपनी साधना ट्रैक करें, प्रगति देखें 🙏",
  }
};

export default lang;
    